language: node_js
os:
  - linux
  - osx
  - windows
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - 12
  - 13
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
scripts:
  - npm i
  - npm run prettier:write
  - npm run lint:write
  - npm run jscpd
  - npm run test
after_script:
  - test $TRAVIS_NODE_VERSION == '12' && test $TRAVIS_OS_NAME == 'linux' && sonar-scanner
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: lunaticthinker-me
    token:
      secure: l9UDWxrjhhebq5Zo6l/hNebMOI9/upFbu1K0JTB1xh8SIVboXudf7Y/XncXYhiamD7p6fG+lrLR5iAbgZeXlBji2qKWL+V0g97Hxcrq3szW6ojjIJf5EaXVSS/CdDMrfH0YxJJEFR2MAqECvhiGbcAJEI/JVeWQJk9Xoy7EWHBSZMXHEF6ddNm2P/YbQHKQ1dcLD3lf33Y4qrVtql5CSy+6Qxk2NDLM5U2rlztFT+bPPkgBRDmybB+G9q4i5zVrEAuX0pj9p0zzp/ybbWg0iON1ndfMY7nRmPtiMYW5DWTNM/1doMD7FoyFjpxWEcDn1Fl9jIKtU0nGVWT8/fDp51I8foEWKdcs0C/zNzMr/Uu6HfACa2rtLmZ2nxMiLzt/dmSbUWP3E+ONDJtlfDgyz6QEvULGs5+4z6iyDX32oEE+J/SMZjlR85+7t4d4qRRwEQPr4Le3II6LYIIjD/bgmZtHPCLZ/25AmGlxOnirncQd1rlAXV6o5L83YA6OwHddWBOMklM9LS1SlQVgIqpUsMPNsSUzix8B9IolL6036bvH9Hlvil16GJR3WoSoqwZ2pMxfBXpN4AuRMz/Yt5G4lVthQO/gBvnqm9+koyHfJPqzPtoxyYo9/NG3H+RbEAku08F3b1JbSb2SafEJoCUVWk0SeLlTAU2s4CBD5CEtBVtY=
