name: Decrypt CI

on:
  workflow_dispatch:
    inputs:
      data_csv:
        type: string
        default: 'Algo,Key,Decrypted,Encrypted,EncryptionError'
        description: CSV Data for Decryption

jobs:
  wait:
    name: Wait
    runs-on: ubuntu-latest
    steps:
    - name: Do nothing
      run: echo "${{ inputs.data_csv }}"
