name: Decrypt CI

on:
  workflow_dispatch:
    inputs:
      data_csv:
        type: string
        default: 'Algo,Key,Decrypted,Encrypted,EncryptionError'
        description: CSV Data for Decryption
      lang:
        type: string
        default: 'JavaScript'
        description: CSV Data for Decryption

jobs:
  wait:
    name: Wait
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Decrypt values from ${{ inputs.lang }} encryption
      run: |
        npm run build \
        && echo "${{ inputs.data_csv }}" | node bin/decrypt.js
