# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          #  error dependency-cruiser@10.0.1: The engine "node" is incompatible with this module. Expected version "^12.20||^14||>=16".
          # - 10.x
          - 12.x
          #  error @babel/eslint-parser@7.14.2: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || >=14.0.0".
          # - 13.x
          - 14.x
          - 15.x
          - 16.x
          - 17.x
          - 18.x
          - 19.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init
        run: npm i
      - name: Code UnitTests
        run: npm run test

  encrypt:
    name: Encrypt
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lang:
          # -cs
          - go
          - js
          # - lua # TODO: no implemented repo yet
          # - py

    steps:
      - uses: actions/checkout@v3
      - name: Code Build
        run: npm i && npm run build
      # https://stackoverflow.com/questions/71952762/how-to-trigger-a-workflow-from-another-workflow-using-github-actions
      - name: Run Generate & Trigger ${{ matrix.lang }} decryption
        run: |
          set -ex; \
          node bin/encrypt.js \
          && DATA_CSV=$(cat ./data.csv | jq -sR .) \
          && JSON_DATA='{"ref":"${{ github.event.repository.default_branch || 'master' }}","inputs":{"data_csv":__DATA_CSV__,"lang":"js"}}' \
          && JSON_DATA=${JSON_DATA/__DATA_CSV__/$DATA_CSV} \
          && echo $JSON_DATA \
          && curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/demo-cross-lang-encryption-${{ matrix.lang }}/actions/workflows/decrypt.yml/dispatches \
          -d "$JSON_DATA"
      # - uses: ./
      #   with:
      #     owner: ${{ github.repository_owner }}
      #     repo: demo-cross-lang-encryption-${{ matrix.lang }}
      #     ref: ${{ github.event.repository.default_branch || 'master' }}
      #     github_token: ${{ secrets.SECRET_PERSONAL_TOKEN }}
      #     workflow_file_name: decrypt.yaml
      #     client_payload: '{"data_csv": "${{env.DATA_CSV}}"}'
      #     # wait_interval: 11
      #     # trigger_workflow: true
      #     # wait_workflow: true
      #     # propagate_failure: true

